FILE = bitcnt_1.c bitcnt_2.c bitcnt_3.c bitcnt_4.c bitcnts.c bitfiles.c bitstrng.c bstr_i.c 

bitcounts: ${FILE} Makefile
	gcc -static ${FILE} -O3 -o bitcounts

clean:
	rm -rf bitcounts bitcounts1 bitcounts2 bitcounts3 bitcounts4 bitcounts5 output*
